insert into room (id, description, name, price, room_type, size) values (1, 'Malignant neoplasm of branchial cleft', 'Drusie', 96.63, 5, 60);
insert into room (id, description, name, price, room_type, size) values (2, 'Obstructive and reflux uropathy, unspecified', 'Armando', 23.3, 0, 46);
insert into room (id, description, name, price, room_type, size) values (3, 'Unspecified injury of left shoulder and upper arm, sequela', 'Kellia', 55.52, 1, 61);
insert into room (id, description, name, price, room_type, size) values (4, 'Oth soft tissue disord related to use/pressure mult sites', 'Gipsy', 34.03, 0, 43);
insert into room (id, description, name, price, room_type, size) values (5, 'Unsp inj unsp musc/fasc/tend at wrs/hnd lv, l hand, sequela', 'Alyse', 28.77, 0, 59);
insert into room (id, description, name, price, room_type, size) values (6, 'Adverse effect of emetics', 'Harbert', 65.52, 5, 46);
insert into room (id, description, name, price, room_type, size) values (7, 'Pnctr w foreign body of finger w/o damage to nail, subs', 'Izzy', 69.56, 5, 32);
insert into room (id, description, name, price, room_type, size) values (8, 'Subluxation of unsp interphaln joint of l idx fngr, init', 'Manda', 24.04, 0, 33);
insert into room (id, description, name, price, room_type, size) values (9, 'Nondisp spiral fx shaft of unsp femr, 7thK', 'Margalit', 54.29, 1, 69);
insert into room (id, description, name, price, room_type, size) values (10, 'Non-prs chr ulc unsp prt of unsp low leg lmt to brkdwn skin', 'Trace', 23.59, 3, 50);
insert into room (id, description, name, price, room_type, size) values (11, 'Unsp Zone I fracture of sacrum, init for clos fx', 'Susana', 31.71, 1, 57);
insert into room (id, description, name, price, room_type, size) values (12, 'Rheumatoid myopathy with rheumatoid arthritis of shoulder', 'Oates', 72.75, 3, 65);
insert into room (id, description, name, price, room_type, size) values (13, 'Encntr for gyn exam (general) (routine) w abnormal findings', 'Archibold', 74.13, 0, 66);
insert into room (id, description, name, price, room_type, size) values (14, 'Dislocation of left scapula, sequela', 'Chev', 85.02, 2, 43);
insert into room (id, description, name, price, room_type, size) values (15, 'Toxic effect of carb monx from utility gas, undet, sequela', 'Mayor', 65.06, 5, 53);
insert into room (id, description, name, price, room_type, size) values (16, 'Oth extrartic fx low end l rad, 7thJ', 'Teodorico', 2.52, 3, 66);
insert into room (id, description, name, price, room_type, size) values (17, 'Abrasion of left back wall of thorax, subsequent encounter', 'Dunn', 43.03, 5, 62);
insert into room (id, description, name, price, room_type, size) values (18, 'Endometriosis of rectovaginal septum and vagina', 'Latia', 56.44, 0, 70);
insert into room (id, description, name, price, room_type, size) values (19, 'Follicular lymphoma, unsp, nodes of head, face, and neck', 'Debby', 99.93, 1, 68);
insert into room (id, description, name, price, room_type, size) values (20, 'Other injuries of lung, unspecified, sequela', 'Janenna', 87.43, 2, 63);
insert into room (id, description, name, price, room_type, size) values (21, 'Hypertrichosis of right lower eyelid', 'Chicky', 50.39, 1, 59);
insert into room (id, description, name, price, room_type, size) values (22, 'Frostbite with tissue necrosis of right ear, sequela', 'Johanna', 46.1, 2, 32);
insert into room (id, description, name, price, room_type, size) values (23, 'Occ of rail trn/veh inj in collisn/hit by roll stok, sequela', 'Brok', 35.03, 1, 63);
insert into room (id, description, name, price, room_type, size) values (24, 'Lacerat intrinsic musc/fasc/tend r idx fngr at wrs/hnd lv', 'Rosabelle', 72.15, 2, 41);
insert into room (id, description, name, price, room_type, size) values (25, 'Unsp fx head of unsp femr, 7thJ', 'Horton', 34.44, 5, 65);
insert into room (id, description, name, price, room_type, size) values (26, 'Inj oth blood vessels at wrs/hnd lv of unsp arm, sequela', 'Stevena', 82.5, 0, 67);
insert into room (id, description, name, price, room_type, size) values (27, 'Unsp occipital condyle fracture, init for opn fx', 'Frants', 50.61, 5, 62);
insert into room (id, description, name, price, room_type, size) values (28, 'Drug-induced myopathy', 'Kattie', 59.14, 3, 59);
insert into room (id, description, name, price, room_type, size) values (29, 'Minor laceration of right internal jugular vein, init encntr', 'Willyt', 77.4, 2, 68);
insert into room (id, description, name, price, room_type, size) values (30, 'Corrosion of first deg mult sites of unsp ankle and foot', 'Annetta', 55.98, 3, 51);
insert into room (id, description, name, price, room_type, size) values (31, 'Other juvenile arthritis, elbow', 'Dotti', 85.09, 5, 36);
insert into room (id, description, name, price, room_type, size) values (32, 'Strain musc/tend post grp at low leg level, right leg, init', 'Papageno', 72.64, 4, 38);
insert into room (id, description, name, price, room_type, size) values (33, 'Snsrnrl hear loss, uni, l ear, with rstrcd hear cntra side', 'Catarina', 80.44, 2, 33);
insert into room (id, description, name, price, room_type, size) values (34, 'Disp fx of neck of fourth metacarpal bone, left hand', 'Rikki', 63.41, 0, 54);
insert into room (id, description, name, price, room_type, size) values (35, 'Toxic effect of paints and dyes, not elsewhere classified', 'Deidre', 37.22, 3, 44);
insert into room (id, description, name, price, room_type, size) values (36, 'Hyphema, bilateral', 'Coralie', 72.7, 3, 58);
insert into room (id, description, name, price, room_type, size) values (37, 'Coma scale, best motor response, abnormal, in the field', 'Natala', 99.8, 0, 53);
insert into room (id, description, name, price, room_type, size) values (38, 'Breakdown (mechanical) of ventricular intracranial shunt', 'Minnaminnie', 33.2, 1, 59);
insert into room (id, description, name, price, room_type, size) values (39, 'Benign neoplasm of mediastinum', 'Grover', 17.05, 2, 70);
insert into room (id, description, name, price, room_type, size) values (40, 'Contracture, left shoulder', 'Vinnie', 75.37, 3, 62);
insert into room (id, description, name, price, room_type, size) values (41, 'Unspecified injury of unspecified kidney, sequela', 'Vladamir', 34.71, 0, 59);
insert into room (id, description, name, price, room_type, size) values (42, 'Corrosion of unsp degree of unspecified elbow, sequela', 'Hinze', 34.88, 0, 52);
insert into room (id, description, name, price, room_type, size) values (43, 'Other and unspecified syphilis', 'Hazlett', 2.77, 5, 42);
insert into room (id, description, name, price, room_type, size) values (44, 'Nondisp fx of lateral malleolus of l fibula, 7thH', 'Raymund', 96.94, 0, 35);
insert into room (id, description, name, price, room_type, size) values (45, 'Exposure to bed fire due to other burning material', 'Irina', 77.84, 2, 49);
insert into room (id, description, name, price, room_type, size) values (46, 'Legal intervnt involving bayonet, bystander injured, subs', 'Herbie', 56.86, 0, 41);
insert into room (id, description, name, price, room_type, size) values (47, 'Sprain of oth parts of lumbar spine and pelvis, subs encntr', 'Gilles', 44.19, 5, 68);
insert into room (id, description, name, price, room_type, size) values (48, 'Lac w/o fb of abd wall, r low q w/o penet perit cav, subs', 'Dorothy', 58.43, 1, 70);
insert into room (id, description, name, price, room_type, size) values (49, 'Adverse effect of tricyclic antidepressants', 'Kinnie', 83.38, 5, 53);
insert into room (id, description, name, price, room_type, size) values (50, 'Contusion of right lower leg, subsequent encounter', 'Petr', 24.4, 3, 35);
insert into room (id, description, name, price, room_type, size) values (51, 'Oth anomalies of tooth position of fully erupted tooth/teeth', 'Caesar', 96.77, 1, 58);
insert into room (id, description, name, price, room_type, size) values (52, 'Unsp athscl native arteries of extremities, right leg', 'De', 37.09, 2, 52);
insert into room (id, description, name, price, room_type, size) values (53, 'Leukemia, unspecified, in relapse', 'Rosella', 39.79, 0, 70);
insert into room (id, description, name, price, room_type, size) values (54, 'Other mastoiditis and related conditions', 'Kass', 76.74, 1, 66);
insert into room (id, description, name, price, room_type, size) values (55, 'Endocrine, nutritional and metabolic diseases comp the puerp', 'Emyle', 89.24, 3, 69);
insert into room (id, description, name, price, room_type, size) values (56, 'Calcium deposit in bursa, unspecified site', 'Bartholomeus', 8.78, 0, 52);
insert into room (id, description, name, price, room_type, size) values (57, 'Post therapeutic collapse of lung status', 'Tierney', 74.48, 3, 34);
insert into room (id, description, name, price, room_type, size) values (58, 'Congenital mitral stenosis', 'Madel', 36.72, 5, 68);
insert into room (id, description, name, price, room_type, size) values (59, 'Poisoning by other antiprotozoal drugs, assault', 'Terrel', 53.44, 2, 67);
insert into room (id, description, name, price, room_type, size) values (60, 'Type 1 diabetes mellitus with circulatory complications', 'Beverie', 75.06, 4, 57);
insert into room (id, description, name, price, room_type, size) values (61, 'Unsp infct of urinary tract in pregnancy, second trimester', 'Silvia', 40.5, 3, 46);
insert into room (id, description, name, price, room_type, size) values (62, 'Drowning and submersion due to oth accident to fishing boat', 'Freddy', 95.55, 5, 64);
insert into room (id, description, name, price, room_type, size) values (63, 'Burn of third degree of ear [any part, except ear drum]', 'Chilton', 37.32, 5, 37);
insert into room (id, description, name, price, room_type, size) values (64, 'Synovial cyst of popliteal space [Baker], right knee', 'Jerrome', 46.86, 2, 41);
insert into room (id, description, name, price, room_type, size) values (65, 'Asphyx due to being trapped in a car trunk, accidental, subs', 'Goddard', 19.92, 2, 59);
insert into room (id, description, name, price, room_type, size) values (66, 'Anomalies of interarch distance', 'Hasheem', 55.15, 5, 61);
insert into room (id, description, name, price, room_type, size) values (67, 'Poisoning by unsp anesthetic, accidental, init', 'Bondie', 4.07, 2, 35);
insert into room (id, description, name, price, room_type, size) values (68, 'Displ transverse fx shaft of unsp ulna, 7thP', 'Vernen', 87.9, 5, 50);
insert into room (id, description, name, price, room_type, size) values (69, 'Traumatic rupture of right radial collateral ligament, subs', 'Roxine', 89.69, 2, 59);
insert into room (id, description, name, price, room_type, size) values (70, 'Radiological devices associated with adverse incidents', 'Banky', 23.85, 3, 67);
insert into room (id, description, name, price, room_type, size) values (71, 'Toxic effect of venom of wasps, self-harm, sequela', 'Berty', 53.89, 5, 69);
insert into room (id, description, name, price, room_type, size) values (72, 'Corrosion of unsp degree of right toe(s) (nail), subs encntr', 'Mitchel', 57.59, 3, 67);
insert into room (id, description, name, price, room_type, size) values (73, 'Unsp fx navicular bone of l wrist, subs for fx w delay heal', 'Leon', 96.97, 4, 37);
insert into room (id, description, name, price, room_type, size) values (74, 'Vesicoureter-reflux w reflux neuropath w/o hydrourt, unil', 'Lazaro', 84.6, 2, 63);
insert into room (id, description, name, price, room_type, size) values (75, 'Toxic effect of phosphorus and its compnd, self-harm, init', 'Tiphany', 89.29, 2, 69);
insert into room (id, description, name, price, room_type, size) values (76, 'Poisoning by oth general anesthetics, accidental, subs', 'Gray', 57.27, 0, 49);
insert into room (id, description, name, price, room_type, size) values (77, 'Nondisp fx of lateral end unsp clavicle, 7thP', 'Birgitta', 17.09, 0, 60);
insert into room (id, description, name, price, room_type, size) values (78, 'Frostbite with tissue necrosis of unspecified hand, sequela', 'Ginnie', 2.04, 2, 30);
insert into room (id, description, name, price, room_type, size) values (79, 'Prsn brd/alit a car injured in collision w statnry object', 'Daniel', 39.75, 0, 65);
insert into room (id, description, name, price, room_type, size) values (80, 'Traumatic rupture of symphysis pubis, sequela', 'Hallie', 99.96, 2, 58);
insert into room (id, description, name, price, room_type, size) values (81, 'Drowning and submersion due to fall off merchant ship, init', 'Saree', 90.05, 0, 37);
insert into room (id, description, name, price, room_type, size) values (82, 'Nondisp suprcndl fx w intrcndl extn low end r femr, 7thE', 'Dario', 6.26, 2, 35);
insert into room (id, description, name, price, room_type, size) values (83, 'Disp fx of body of hamate bone, left wrist, init for opn fx', 'Andonis', 38.39, 2, 32);
insert into room (id, description, name, price, room_type, size) values (84, 'Subluxation of interphalangeal joint of unsp great toe, subs', 'Land', 67.95, 2, 51);
insert into room (id, description, name, price, room_type, size) values (85, 'Corrosion of unsp degree of right shoulder, init encntr', 'Layne', 40.08, 4, 52);
insert into room (id, description, name, price, room_type, size) values (86, 'Corrosion of third degree of right ankle, sequela', 'Jonas', 33.28, 1, 58);
insert into room (id, description, name, price, room_type, size) values (87, 'Oth diabetes mellitus with other specified complications', 'Caryn', 79.3, 3, 49);
insert into room (id, description, name, price, room_type, size) values (88, 'Nondisp fx of base of neck of unsp femur, init for clos fx', 'Broderic', 22.03, 5, 50);
insert into room (id, description, name, price, room_type, size) values (89, 'Oth injury of other blood vessels at wrist and hand level', 'Marie-jeanne', 35.83, 2, 59);
insert into room (id, description, name, price, room_type, size) values (90, 'Laceration w foreign body of finger w/o damage to nail, subs', 'Garey', 3.77, 1, 53);
insert into room (id, description, name, price, room_type, size) values (91, 'Unsp fx shaft of left ulna, subs for clos fx w malunion', 'Nikoletta', 53.65, 1, 52);
insert into room (id, description, name, price, room_type, size) values (92, 'Nondisp fx of coronoid pro of l ulna, 7thR', 'Amalia', 62.47, 0, 30);
insert into room (id, description, name, price, room_type, size) values (93, 'Displ seg fx shaft of r femr, 7thH', 'Amabel', 31.14, 3, 47);
insert into room (id, description, name, price, room_type, size) values (94, 'Oth types of follicular lymphoma, intrathoracic lymph nodes', 'Parker', 30.98, 3, 64);
insert into room (id, description, name, price, room_type, size) values (95, 'Insect bite (nonvenomous) of scrotum and testes, init encntr', 'Milli', 60.54, 4, 50);
insert into room (id, description, name, price, room_type, size) values (96, 'Fracture of orbital floor, unspecified side', 'Marchall', 33.46, 2, 58);
insert into room (id, description, name, price, room_type, size) values (97, 'Abnormal urine levels of substances chiefly nonmed source', 'Lucky', 28.69, 1, 67);
insert into room (id, description, name, price, room_type, size) values (98, 'Prsn brd/alit pk-up/van inj in clsn w nonmtr vehicle, subs', 'Lucius', 64.68, 5, 59);
insert into room (id, description, name, price, room_type, size) values (99, 'Chagas'' disease (chronic) with nervous system involvement', 'Norry', 3.92, 5, 57);
insert into room (id, description, name, price, room_type, size) values (100, '4-part fx surg neck of unsp humerus, subs for fx w malunion', 'Henrieta', 7.23, 5, 57);
SELECT setval('room_seq', (SELECT MAX(id) FROM room));
